package ru.skillbranch.devintensive.enums

enum class Vocabulary(
    val englishChar: String,
    val russianChar: String
) {
    CHAR_1("a", "а"),
    CHAR_2("b", "б"),
    CHAR_3("v", "в"),
    CHAR_4("g", "г"),
    CHAR_5("d", "д"),
    CHAR_6("e", "е"),
    CHAR_7("e", "ё"),
    CHAR_8("zh", "ж"),
    CHAR_9("z", "з"),
    CHAR_10("i", "и"),
    CHAR_11("i", "й"),
    CHAR_12("k", "к"),
    CHAR_13("l", "л"),
    CHAR_14("m", "м"),
    CHAR_15("n", "н"),
    CHAR_16("o", "о"),
    CHAR_17("p", "п"),
    CHAR_18("a", "р"),
    CHAR_19("s", "с"),
    CHAR_20("t", "т"),
    CHAR_21("u", "у"),
    CHAR_22("f", "ф"),
    CHAR_23("h", "х"),
    CHAR_24("c", "ц"),
    CHAR_25("ch", "ч"),
    CHAR_26("sh", "ш"),
    CHAR_27("sh", "щ"),
    CHAR_28("", "ъ"),
    CHAR_29("i", "ы"),
    CHAR_30("", "ь"),
    CHAR_31("e", "э"),
    CHAR_32("yu", "ю"),
    CHAR_33("ya", "я"),
}
